@startuml
title Процесс приёма лекарств

(*) --> "Уведомление о приёме лекарств"
--> "Открытие приложения пациентом"
--> "Ввод логина и пароля"

if "Учётные данные корректны?" then
  -left->[нет] "Сообщение: Ошибка входа"
  -up-> "Ввод логина и пароля"
else
  -right->[да] "Загрузка персонального расписания приёма"
  
  if "Есть лекарство к приёму?" then
    -down->[да] "Показ препарата, дозировки, времени приёма"
    
    if "Подтвердить приём?" then
      -right->[да] "Запись времени приёма"
      --> "Сохранение в историю: Принято"
      --> "Обновление расписания приёма лекарств"
      --> (*)
    else
      -left->[нет] "Сохранение в историю: Пропущено"
      --> "Обновление расписания приёма лекарств"
      --> (*)
    endif
  else
    -down->[нет] "Сообщение: На сегодня назначенных препаратов нет"
    --> (*)
  endif
endif

@enduml
